version: '2.0'
services:
    database:
        container_name: database
        image: mysql:5.7
        ports:
           - "3306:3306"
        command: --init-file /Database/init.sql
        environment:
           MYSQL_ROOT_PASSWORD: root
           MYSQL_ROOT_PASSWORD: root
           MYSQL_USER: root
           MYSQL_PASSWORD: root
    eureka-server:
        container_name: eureka-server
        build:
            context: .
            dockerfile: Docker-EurekaServer
        image: eureka-server
        expose:
            - 1111
        ports:
            - 80:1111
        networks:
            - emp-network
    expense-code:
        container_name: expense-code
        depends_on:
            - eureka-server
            - database
        links:
            - eureka-server
            - database
        build:
            context: .
            dockerfile: Docker-ExpenseCode
        environment:
            eureka.client.serviceUrl.defaultZone: http://eureka-server:1111/eureka
            spring.datasource.url=jdbc:mysql://database:3306/expensedb
            spring.datasource.username=root
            spring.datasource.password=root
        image: expense-code
        expose:
            - 2222
        ports:
            - 2222:2222
        networks:
            - emp-network
    project-code:
        container_name: project-code
        depends_on:
            - eureka-server
            - database
        links:
            - eureka-server
            - database
        build:
            context: .
            dockerfile: Docker-ProjectCode
        environment:
            eureka.client.serviceUrl.defaultZone: http://eureka-server:1111/eureka
        image: project-code
        expose:
            - 4444
        ports:
            - 4444:4444
        networks:
            - emp-network
    employee-detail:
        container_name: employee-detail
        depends_on:
            - eureka-server
            - database
        links:
            - eureka-server
            - database
        build:
            context: .
            dockerfile: Docker-EmployeeDetail
        environment:
            eureka.client.serviceUrl.defaultZone: http://eureka-server:1111/eureka
        image: employee-detail
        expose:
            - 5555
        ports:
            - 5555:5555
        networks:
            - emp-network
    expense-detail:
        container_name: expense-detail
        depends_on:
            - eureka-server
            - database
        links:
            - eureka-server
            - expense-code
            - project-code
            - employee-detail
            - database
        build:
            context: .
            dockerfile: Docker-ExpenseDetail
        environment:
            eureka.client.serviceUrl.defaultZone: http://eureka-server:1111/eureka
        image: expense-detail
        expose:
            - 2222
        ports:
            - 2222:2222
        networks:
            - emp-network
networks:
    emp-network:
        driver: bridge